name: gaming_app_ui
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  convex_bottom_bar: ^3.2.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true


  assets:
    - images/
    
 
  fonts:
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
       
    - family: Poppins Italic
      fonts:
        - asset: fonts/Poppins-italic.ttf
  
    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
     
    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
